export const ApiConst = Object.freeze({
  webLogin: "api/Login/LoginO",
  getFile: "api/File/GetById",
  download: "api/File/Download",
  upload: "api/File/Upload",
  insert: "api/File/Insert",
  getAllCompany: "api/Company/GetAll",
  getAllSetting: "api/Setting/GetAll",
  insertSetting: "api/Setting/Insert",
  getAllMenu: "api/Menu/GetAll",
  getAllFirstPrugTemplate: "api/ProgramTemplate/GetAll",
  getAllCommand: "api/Command/GetAll",
  getAllProgramTemplate: "api/ProgramTemplate/GetAll",
  getAllWfTemplate: "api/WFTemplate/GetAll",
  getAllEntityType: "api/EntityType/GetAllComplete",
  getAllAfBtn:"api/AFBtn/GetAll",
  insertAfBtn:"api/AFBtn/Insert",
});
